version: '2'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    privileged: true
    labels:
      io.resin.features.dbus: '1'
    ports:
      - "80:80"
  data:
    container_name: data
    build: ./data
    labels:
      io.resin.features.dbus: '1'
    ports:
      - "4242:4242"
  wifi-connect:
      build: ./wifi-connect
      privileged: true
      network_mode: "host"
      labels:
        io.resin.features.dbus: '1'

