version: '2'
services:
  frontend:
    container_name: front
    build: ./frontend
    ports:
      - 5001:80
    links:
      - data
    networks:
      - backend
  data:
    container_name: back
    build: ./data
    ports:
      - 4242:4242
    networks:
      - backend
networks:
  backend:
    driver: bridge



