version: '2'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    privileged: true
    ports:
      - "80:80"
  data:
    container_name: data
    build: ./data
    ports:
      - "4242:4242"


