FROM resin/%%RESIN_MACHINE_NAME%%-python:3.5.5-onbuild

# Defines our working directory in container
WORKDIR /usr/src/app

# Install required Python packages
RUN pip install --upgrade pip

# Install required Python packages
RUN pip install -U \
 zerorpc \
 arrow \
 pyyaml

# This will copy all files in our root to the working  directory in the container
COPY . ./

COPY env_vars.yaml /data/env_vars.yaml

# server.js will run when container starts up on the device
CMD ["python", "backend.py"]